using Vertr.TinvestGateway.Contracts.Portfolios;

namespace Vertr.TinvestGateway.Converters;

internal static class OperationEnumsConverter
{
    public static TradeOperationType Convert(this Tinkoff.InvestApi.V1.OperationType source)
        => source switch
        {
            Tinkoff.InvestApi.V1.OperationType.Unspecified => TradeOperationType.Unspecified,
            Tinkoff.InvestApi.V1.OperationType.Input => TradeOperationType.Input,
            Tinkoff.InvestApi.V1.OperationType.BondTax => TradeOperationType.BondTax,
            Tinkoff.InvestApi.V1.OperationType.OutputSecurities => TradeOperationType.OutputSecurities,
            Tinkoff.InvestApi.V1.OperationType.Overnight => TradeOperationType.Overnight,
            Tinkoff.InvestApi.V1.OperationType.Tax => TradeOperationType.Tax,
            Tinkoff.InvestApi.V1.OperationType.BondRepaymentFull => TradeOperationType.BondRepaymentFull,
            Tinkoff.InvestApi.V1.OperationType.SellCard => TradeOperationType.SellCard,
            Tinkoff.InvestApi.V1.OperationType.DividendTax => TradeOperationType.DividendTax,
            Tinkoff.InvestApi.V1.OperationType.Output => TradeOperationType.Output,
            Tinkoff.InvestApi.V1.OperationType.BondRepayment => TradeOperationType.BondRepayment,
            Tinkoff.InvestApi.V1.OperationType.TaxCorrection => TradeOperationType.TaxCorrection,
            Tinkoff.InvestApi.V1.OperationType.ServiceFee => TradeOperationType.ServiceFee,
            Tinkoff.InvestApi.V1.OperationType.BenefitTax => TradeOperationType.BenefitTax,
            Tinkoff.InvestApi.V1.OperationType.MarginFee => TradeOperationType.MarginFee,
            Tinkoff.InvestApi.V1.OperationType.Buy => TradeOperationType.Buy,
            Tinkoff.InvestApi.V1.OperationType.BuyCard => TradeOperationType.BuyCard,
            Tinkoff.InvestApi.V1.OperationType.InputSecurities => TradeOperationType.InputSecurities,
            Tinkoff.InvestApi.V1.OperationType.SellMargin => TradeOperationType.SellMargin,
            Tinkoff.InvestApi.V1.OperationType.BrokerFee => TradeOperationType.BrokerFee,
            Tinkoff.InvestApi.V1.OperationType.BuyMargin => TradeOperationType.BuyMargin,
            Tinkoff.InvestApi.V1.OperationType.Dividend => TradeOperationType.Dividend,
            Tinkoff.InvestApi.V1.OperationType.Sell => TradeOperationType.Sell,
            Tinkoff.InvestApi.V1.OperationType.Coupon => TradeOperationType.Coupon,
            Tinkoff.InvestApi.V1.OperationType.SuccessFee => TradeOperationType.SuccessFee,
            Tinkoff.InvestApi.V1.OperationType.DividendTransfer => TradeOperationType.DividendTransfer,
            Tinkoff.InvestApi.V1.OperationType.AccruingVarmargin => TradeOperationType.AccruingVarmargin,
            Tinkoff.InvestApi.V1.OperationType.WritingOffVarmargin => TradeOperationType.WritingOffVarmargin,
            Tinkoff.InvestApi.V1.OperationType.DeliveryBuy => TradeOperationType.DeliveryBuy,
            Tinkoff.InvestApi.V1.OperationType.DeliverySell => TradeOperationType.DeliverySell,
            Tinkoff.InvestApi.V1.OperationType.TrackMfee => TradeOperationType.TrackMfee,
            Tinkoff.InvestApi.V1.OperationType.TrackPfee => TradeOperationType.TrackPfee,
            Tinkoff.InvestApi.V1.OperationType.TaxProgressive => TradeOperationType.TaxProgressive,
            Tinkoff.InvestApi.V1.OperationType.BondTaxProgressive => TradeOperationType.BondTaxProgressive,
            Tinkoff.InvestApi.V1.OperationType.DividendTaxProgressive => TradeOperationType.DividendTaxProgressive,
            Tinkoff.InvestApi.V1.OperationType.BenefitTaxProgressive => TradeOperationType.BenefitTaxProgressive,
            Tinkoff.InvestApi.V1.OperationType.TaxCorrectionProgressive => TradeOperationType.TaxCorrectionProgressive,
            Tinkoff.InvestApi.V1.OperationType.TaxRepoProgressive => TradeOperationType.TaxRepoProgressive,
            Tinkoff.InvestApi.V1.OperationType.TaxRepo => TradeOperationType.TaxRepo,
            Tinkoff.InvestApi.V1.OperationType.TaxRepoHold => TradeOperationType.TaxRepoHold,
            Tinkoff.InvestApi.V1.OperationType.TaxRepoRefund => TradeOperationType.TaxRepoRefund,
            Tinkoff.InvestApi.V1.OperationType.TaxRepoHoldProgressive => TradeOperationType.TaxRepoHoldProgressive,
            Tinkoff.InvestApi.V1.OperationType.TaxRepoRefundProgressive => TradeOperationType.TaxRepoRefundProgressive,
            Tinkoff.InvestApi.V1.OperationType.DivExt => TradeOperationType.DivExt,
            Tinkoff.InvestApi.V1.OperationType.TaxCorrectionCoupon => TradeOperationType.TaxCorrectionCoupon,
            Tinkoff.InvestApi.V1.OperationType.CashFee => TradeOperationType.CashFee,
            Tinkoff.InvestApi.V1.OperationType.OutFee => TradeOperationType.OutFee,
            Tinkoff.InvestApi.V1.OperationType.OutStampDuty => TradeOperationType.OutStampDuty,
            Tinkoff.InvestApi.V1.OperationType.OutputSwift => TradeOperationType.OutputSwift,
            Tinkoff.InvestApi.V1.OperationType.InputSwift => TradeOperationType.InputSwift,
            Tinkoff.InvestApi.V1.OperationType.OutputAcquiring => TradeOperationType.OutputAcquiring,
            Tinkoff.InvestApi.V1.OperationType.InputAcquiring => TradeOperationType.InputAcquiring,
            Tinkoff.InvestApi.V1.OperationType.OutputPenalty => TradeOperationType.OutputPenalty,
            Tinkoff.InvestApi.V1.OperationType.AdviceFee => TradeOperationType.AdviceFee,
            Tinkoff.InvestApi.V1.OperationType.TransIisBs => TradeOperationType.TransIisBs,
            Tinkoff.InvestApi.V1.OperationType.TransBsBs => TradeOperationType.TransBsBs,
            Tinkoff.InvestApi.V1.OperationType.OutMulti => TradeOperationType.OutMulti,
            Tinkoff.InvestApi.V1.OperationType.InpMulti => TradeOperationType.InpMulti,
            Tinkoff.InvestApi.V1.OperationType.OverPlacement => TradeOperationType.OverPlacement,
            Tinkoff.InvestApi.V1.OperationType.OverCom => TradeOperationType.OverCom,
            Tinkoff.InvestApi.V1.OperationType.OverIncome => TradeOperationType.OverIncome,
            Tinkoff.InvestApi.V1.OperationType.OptionExpiration => TradeOperationType.OptionExpiration,
            Tinkoff.InvestApi.V1.OperationType.FutureExpiration => TradeOperationType.FutureExpiration,
            _ => throw new NotImplementedException(),
        };
}
